use std::sync::Arc;

use axum::{
    extract::State,
    http::StatusCode,
    response::{IntoResponse, Response},
    Extension, Json,
};
use serde_json::{json, Value};

use crate::mcp::identity::{CallerIdentity, IdentityError};
use crate::mcp::trajectory;
use crate::mcp::McpState;
use chrono::Utc;

use super::epics;
use super::learnings;
use super::managed_feeds;
use super::repo_rag;
use super::tasks;
use super::types::{tool_error, JsonRpcRequest, JsonRpcResponse};

/// MCP protocol version this server speaks natively.
const SERVER_PROTOCOL_VERSION: &str = "2025-06-18";

/// Older protocol versions we still understand. If a client offers one of these
/// during `initialize`, we echo it back so the session uses that version
/// (graceful downgrade per spec §Initialization).
const SUPPORTED_PROTOCOL_VERSIONS: &[&str] = &["2025-06-18", "2024-11-05"];

// ---------------------------------------------------------------------------
// Tool registry macro
// ---------------------------------------------------------------------------

/// Register all MCP tools in one place. Expands to:
/// - `fn tool_definitions() -> Value` — the JSON tool list
/// - `async fn dispatch_tool(...)` — the match dispatch
/// - `pub const TOOL_NAMES: &[&str]` — flat list of names
macro_rules! mcp_tools {
    (
        $(
            $kind:ident $name:literal => $handler:path,
                $desc:literal,
                $schema:tt
        );+ $(;)?
    ) => {
        pub(super) fn tool_definitions() -> Value {
            json!({
                "tools": [
                    $(
                        {
                            "name": $name,
                            "description": $desc,
                            "inputSchema": $schema
                        }
                    ),+
                ]
            })
        }

        pub(super) async fn dispatch_tool(
            state: &McpState,
            id: Option<Value>,
            identity: &CallerIdentity,
            tool_name: &str,
            args: Value,
        ) -> JsonRpcResponse {
            match tool_name {
                $(
                    $name => mcp_tools!(@call $kind, $handler, state, id, identity, args),
                )+
                other => JsonRpcResponse::err(id, -32602, format!("Unknown tool: {other}")),
            }
        }

        pub const TOOL_NAMES: &[&str] = &[$($name),+];
    };

    (@call sync, $handler:path, $state:expr, $id:expr, $identity:expr, $args:expr) => {
        $handler($state, $id, $identity, $args)
    };
    (@call async, $handler:path, $state:expr, $id:expr, $identity:expr, $args:expr) => {
        $handler($state, $id, $identity, $args).await
    };
}

// ---------------------------------------------------------------------------
// Tool definitions & dispatch (generated by mcp_tools!)
// ---------------------------------------------------------------------------

mcp_tools! {
    async "update_task" => tasks::handle_update_task,
        "Update a task's status, sub_status, title, description, repo_path, plan, and/or PR fields. At least one field besides task_id must be provided.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID"
                },
                "status": {
                    "type": "string",
                    "description": "New status: backlog, running, or review. Setting done is not allowed via MCP — ask the human operator to move the task to done from the TUI.",
                    "enum": ["backlog", "running", "review"]
                },
                "plan_path": {
                    "type": "string",
                    "description": "Absolute file path to the implementation plan"
                },
                "title": {
                    "type": "string",
                    "description": "New title for the task"
                },
                "description": {
                    "type": "string",
                    "description": "New description for the task"
                },
                "repo_path": {
                    "type": "string",
                    "description": "New repository path for the task"
                },
                "sort_order": {
                    "type": "integer",
                    "description": "Display order within column (lower values appear first)"
                },
                "url": {
                    "type": "string",
                    "description": "URL associated with this task (PR, issue, security alert, or other link). Pass an empty string to clear it. When set to a non-empty value, url_type is required."
                },
                "url_type": {
                    "type": "string",
                    "description": "Type of the url: 'pr' (pull request — enables PR polling/merge), 'security_alert', 'issue', or 'other'. Required when url is set.",
                    "enum": ["pr", "security_alert", "issue", "other"]
                },
                "tag": {
                    "type": "string",
                    "description": "Task tag: bug, feature, chore, pr-review, research, fix, or dependabot. Controls dispatch behavior. The dependabot tag is intended for feed scripts only — TUI users cannot select it from the tag picker.",
                    "enum": ["bug", "feature", "chore", "pr-review", "research", "fix", "dependabot"]
                },
                "sub_status": {
                    "type": "string",
                    "description": "Sub-status within the current status column. Running: active, needs_input, stale, crashed. Review: awaiting_review, changes_requested, approved. Must be valid for the task's current (or new) status.",
                    "enum": ["none", "active", "needs_input", "stale", "crashed", "conflict", "awaiting_review", "changes_requested", "approved"]
                },
                "epic_id": {
                    "type": "integer",
                    "description": "Link this task to an epic by ID"
                },
                "base_branch": {
                    "type": "string",
                    "description": "The base branch for rebase and PR operations (e.g. 'main', 'develop'). Defaults to 'main' if not specified."
                },
                "wrap_up_mode": {
                    "type": ["string", "null"],
                    "description": "Pre-set the wrap-up action for this task: 'rebase' (rebase onto base_branch), 'pr' (create a PR), or 'done' (mark done immediately). Pass null to clear.",
                    "enum": ["rebase", "pr", "done", null]
                },
                "auto_run_plan": {
                    "type": "boolean",
                    "description": "When true and the task has a plan_path, the dispatched agent implements the plan immediately instead of asking for confirmation first."
                }
            },
            "required": ["task_id"]
        };

    async "get_task" => tasks::handle_get_task,
        "Get details about a task",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID"
                }
            },
            "required": ["task_id"]
        };

    async "create_task" => tasks::handle_create_task,
        "Create a new task on the kanban board. Tasks always start in 'backlog' status. Caller identity is provided by the dispatch HTTP transport (X-Caller-Task-Id for dispatched agents, X-Caller-Kind: session for non-dispatched sessions) — you do NOT pass a caller_task_id argument. Dispatched agents: the new task inherits epic_id from your task; pass epic_id explicitly to override (epic_id: null clears epic).",
        {
            "type": "object",
            "properties": {
                "title": {
                    "type": "string",
                    "description": "Task title"
                },
                "repo_path": {
                    "type": "string",
                    "description": "Path to the repository for this task"
                },
                "description": {
                    "type": "string",
                    "description": "Task description (optional, defaults to empty)"
                },
                "plan_path": {
                    "type": "string",
                    "description": "Absolute file path to the implementation plan (optional)."
                },
                "epic_id": {
                    "type": ["integer", "null"],
                    "description": "Override the inherited epic. Omit to inherit from the caller's task (when the caller is a dispatched agent). Pass null explicitly to create a task with no epic even when the caller has one."
                },
                "sort_order": {
                    "type": "integer",
                    "description": "Display order within column (lower values appear first)"
                },
                "tag": {
                    "type": "string",
                    "description": "Task tag: bug, feature, chore, pr-review, research, fix, or dependabot. Controls dispatch behavior. The dependabot tag is intended for feed scripts only — TUI users cannot select it from the tag picker.",
                    "enum": ["bug", "feature", "chore", "pr-review", "research", "fix", "dependabot"]
                },
                "base_branch": {
                    "type": "string",
                    "description": "The base branch for rebase and PR operations (e.g. 'main', 'develop'). Defaults to 'main' if not specified."
                },
                "wrap_up_mode": {
                    "type": "string",
                    "description": "Pre-set the wrap-up action for this task: 'rebase' (rebase onto base_branch), 'pr' (create a PR), or 'done' (mark done immediately).",
                    "enum": ["rebase", "pr", "done"]
                },
                "auto_run_plan": {
                    "type": "boolean",
                    "description": "When true and a plan_path is set, the dispatched agent implements the plan immediately instead of summarizing it and asking for confirmation first. Use only when the plan has already been reviewed (e.g. by the decompose-review skill's work-package confirmation step). Defaults to false."
                }
            },
            "required": ["title", "repo_path"]
        };

    async "list_tasks" => tasks::handle_list_tasks,
        "List tasks on the kanban board. Filters are ANDed. When called by a dispatched agent, results auto-scope to the agent's epic and exclude the agent's own task; passing explicit epic_id/repo_paths disables auto-scoping. When called from a non-dispatched session, no auto-scoping. Output includes PR URL and plan goal when available.",
        {
            "type": "object",
            "properties": {
                "status": {
                    "description": "Filter by status. Single string or array of strings.",
                    "oneOf": [
                        { "type": "string", "enum": ["backlog", "running", "review", "done", "archived"] },
                        { "type": "array", "items": { "type": "string", "enum": ["backlog", "running", "review", "done", "archived"] } }
                    ]
                },
                "epic_id": {
                    "type": "integer",
                    "description": "Filter to only tasks belonging to this epic."
                },
                "repo_paths": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Filter to tasks whose repo_path is in this list."
                }
            }
        };

    async "create_epic" => epics::handle_create_epic,
        "Create a new epic on the kanban board.",
        {
            "type": "object",
            "properties": {
                "title": { "type": "string", "description": "Epic title" },
                "description": { "type": "string", "description": "Epic description" },
                "sort_order": { "type": "integer", "description": "Display order within column (lower values appear first)" },
                "parent_epic_id": { "type": "integer", "description": "Optional parent epic ID. When set, this epic becomes a sub-epic of the specified parent. Cannot be set to the epic's own ID (self-referential cycles are rejected by the database)." }
            },
            "required": ["title"]
        };

    async "get_epic" => epics::handle_get_epic,
        "Get details about an epic including its subtask summary.",
        {
            "type": "object",
            "properties": {
                "epic_id": { "type": "integer", "description": "The epic ID" }
            },
            "required": ["epic_id"]
        };

    async "list_epics" => epics::handle_list_epics,
        "List all epics on the kanban board.",
        { "type": "object", "properties": {} };

    async "update_epic" => epics::handle_update_epic,
        "Update an epic's title, description, status, plan, sort order, feed configuration, or parent epic.",
        {
            "type": "object",
            "properties": {
                "epic_id": { "type": "integer", "description": "The epic ID" },
                "title": { "type": "string", "description": "New title" },
                "description": { "type": "string", "description": "New description" },
                "status": { "type": "string", "description": "New status: backlog, running, review, or done", "enum": ["backlog", "running", "review", "done"] },
                "plan_path": { "type": "string", "description": "Path to the plan file" },
                "sort_order": { "type": "integer", "description": "Display order within column (lower values appear first)" },
                "feed_command": { "type": ["string", "null"], "description": "Shell command that emits JSON FeedItems to populate tasks. Pass null to clear." },
                "feed_interval_secs": { "type": ["integer", "null"], "description": "Polling interval in seconds (overrides the default). Pass null to clear." },
                "group_by_repo": { "type": "boolean", "description": "When true, group feed tasks by repository path in the TUI. Pass false to disable grouping." },
                "parent_epic_id": { "type": ["integer", "null"], "description": "Re-parent this epic under another epic by ID. Pass null to make it a root epic. Cycle detection prevents hierarchical loops." }
            },
            "required": ["epic_id"]
        };

    async "wrap_up" => tasks::handle_wrap_up,
        "Wrap up a running or review task. All three actions (rebase, done, pr) leave the task \
running and return an exit token you MUST pass to exit_session — the terminal transition (Done, \
or Review with the PR url) happens there, not here. \
'rebase' rebases onto base_branch and fast-forwards it (blocks until complete). \
'done' performs no git operations. \
'pr' performs no git operations — the agent runs git push and gh pr create itself, then passes \
the resulting URL to exit_session (not to wrap_up).",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID to wrap up"
                },
                "action": {
                    "type": "string",
                    "enum": ["rebase", "done", "pr"],
                    "description": "'rebase' — rebase onto base_branch and fast-forward it. 'done' — no git ops. 'pr' — no git ops; agent has already run gh pr create. All three return an exit token; the task stays in its current status until exit_session closes it."
                }
            },
            "required": ["task_id", "action"]
        };

    async "dispatch_task" => tasks::handle_dispatch_task,
        "Dispatch a backlog task by ID. Creates a worktree from the task's base branch and launches a tmux session. Waits for the dispatch to complete and returns success with worktree path and tmux window, or an error if the task is not in backlog status or the dispatch fails.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The task ID to dispatch"
                }
            },
            "required": ["task_id"]
        };

    async "subscribe_to_task" => tasks::handle_subscribe_to_task,
        "Subscribe to be notified when another task finishes (reaches Done or Archived) or is deleted first. If the target has already finished, you're told immediately instead of being subscribed. Delivery is a one-shot tmux nudge (write_message_file + notify_tmux).",
        {
            "type": "object",
            "properties": {
                "watcher_task_id": { "type": "integer", "description": "Your own task ID (the one to notify)" },
                "target_task_id": { "type": "integer", "description": "ID of the task to watch for completion" }
            },
            "required": ["watcher_task_id", "target_task_id"]
        };

    async "unsubscribe_from_task" => tasks::handle_unsubscribe_from_task,
        "Cancel a previously registered subscribe_to_task watch. Idempotent — succeeds even if no such subscription exists.",
        {
            "type": "object",
            "properties": {
                "watcher_task_id": { "type": "integer", "description": "Your own task ID" },
                "target_task_id": { "type": "integer", "description": "ID of the task you were watching" }
            },
            "required": ["watcher_task_id", "target_task_id"]
        };

    async "record_learning" => learnings::handle_record_learning,
        "Record a new entry in the shared knowledge base. The entry is immediately active and will be injected into future dispatch prompts for agents working in the matching scope. Omit scope_ref to auto-derive it from the calling task (recommended in most cases). summary/detail must not cite a specific file, symbol, or line number — those belong in the Allium spec or a Rust doc comment, where check-doc-symbols.sh keeps them accurate; describe the durable behavior instead.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "ID of the task this learning was discovered during"
                },
                "kind": {
                    "type": "string",
                    "description": "Category: pitfall, convention, preference, tool_recommendation, procedural, or landscape",
                    "enum": crate::models::LearningKind::ALL.iter().map(|k| k.as_str()).collect::<Vec<_>>()
                },
                "summary": {
                    "type": "string",
                    "description": "One-sentence description of what was learned (required, non-empty)"
                },
                "scope": {
                    "type": "string",
                    "description": "Scope this learning applies to: user (global), repo, epic, or task",
                    "enum": crate::models::LearningScope::ALL.iter().map(|s| s.as_str()).collect::<Vec<_>>()
                },
                "detail": {
                    "type": "string",
                    "description": "Optional extended context or explanation"
                },
                "scope_ref": {
                    "type": "string",
                    "description": "Qualifier for the scope (e.g. repo path, epic ID as string). Omit to auto-derive from the calling task — only set explicitly when recording a learning about a different context than the current task."
                },
                "tags": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Optional free-form labels for filtering (e.g. [\"rust\", \"testing\"])"
                }
            },
            "required": ["task_id", "kind", "summary", "scope"]
        };

    async "query_learnings" => learnings::handle_query_learnings,
        "Query the knowledge base for entries relevant to the current task's context using semantic search (RAG). Excludes task-scoped entries.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "ID of the calling task — determines which repo/project/epic to use for scope boosting"
                },
                "query": {
                    "type": "string",
                    "description": "Optional semantic query string. When omitted, the task's title and description are used as the query."
                },
                "tag_filter": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "Optional list of tags to soft-boost — learnings with matching tags score higher but untagged entries are not excluded"
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum number of results to return (default 50, max 50)"
                }
            },
            "required": ["task_id"]
        };

    async "rate_learning" => learnings::handle_rate_learning,
        "Give feedback on a knowledge base entry that was surfaced to you this task. \
Call any time you act on a retrieved learning. 'helped' upvotes it (a usefulness signal that \
boosts ranking); 'wrong' downvotes it (may go negative) — neither changes its status, and \
there is no human review step. You can only rate a learning that was surfaced to you (injected \
into your prompt or returned by query_learnings).",
        {
            "type": "object",
            "properties": {
                "learning_id": {
                    "type": "integer",
                    "description": "ID of the knowledge base entry to rate"
                },
                "task_id": {
                    "type": "integer",
                    "description": "ID of the task that acted on this entry"
                },
                "verdict": {
                    "type": "string",
                    "enum": ["helped", "wrong"],
                    "description": "'helped' — the entry applied and was useful (upvotes it). 'wrong' — the entry misled you or is inaccurate (downvotes it; may go negative). Neither changes the entry's status."
                }
            },
            "required": ["learning_id", "task_id", "verdict"]
        };

    async "delete_learning" => learnings::handle_delete_learning,
        "Delete a learning entry from the knowledge base by ID. \
Returns an error if the ID does not exist.",
        {
            "type": "object",
            "properties": {
                "learning_id": {
                    "type": "integer",
                    "description": "ID of the knowledge base entry to delete"
                }
            },
            "required": ["learning_id"]
        };

    async "get_managed_feed_config" => managed_feeds::handle_get_managed_feed_config,
        "Return the current managed-feed configuration: the PR-reviews and CVE \
feed commands and their poll intervals (in seconds). Unset values are reported as unset.",
        { "type": "object", "properties": {} };

    async "set_managed_feed_config" => managed_feeds::handle_set_managed_feed_config,
        "Set or clear the managed-feed configuration (PR-reviews and CVE feed commands + poll \
intervals). Each field is triple-state: omit to leave unchanged, pass null to clear, or pass a \
value to set. Saving re-provisions the managed epic tree, so enabling a feed creates its epics \
immediately. Intervals are in seconds; omit an interval to fall back to the default feed interval.",
        {
            "type": "object",
            "properties": {
                "reviews_command": { "type": ["string", "null"], "description": "Script emitting the involved-PR feed. Pass null to clear (disables the reviews subtree)." },
                "reviews_interval_secs": { "type": ["integer", "null"], "description": "Poll cadence for the reviews feed, in seconds. Pass null to clear (falls back to the default)." },
                "cve_command": { "type": ["string", "null"], "description": "Script emitting the security/CVE feed. Pass null to clear (disables the CVE epic)." },
                "cve_interval_secs": { "type": ["integer", "null"], "description": "Poll cadence for the CVE feed, in seconds. Pass null to clear (falls back to the default)." }
            }
        };

    async "set_verify_command" => tasks::handle_set_verify_command,
        "Set or clear the verify command for a repository path. \
The command is injected into future agent prompts as a mandatory pre-completion check. \
Pass command=null to clear it.",
        {
            "type": "object",
            "properties": {
                "repo_path": {
                    "type": "string",
                    "description": "Absolute path to the repository root (e.g. the task's repo_path)"
                },
                "command": {
                    "type": "string",
                    "description": "Single-line shell command to run for verification. Omit or pass null to clear."
                }
            },
            "required": ["repo_path"]
        };

    async "exit_session" => tasks::handle_exit_session,
        "Close your agent session in a single call — this is the final step of wrap-up, called after \
the commit and after any reflection the wrap-up flow has already run. Applies the terminal mutation atomically with clearing the tmux \
window: 'rebase'/'done' move the task to Done; 'pr' moves it to Review and sets the PR url. The \
action must match the action passed to wrap_up, or the call is rejected. \
If the task belongs to an epic with auto_dispatch enabled, closing it automatically dispatches \
that epic's next backlog subtask — there is no tool for you to call, and you must not try to \
dispatch it yourself. \
Read the response text: on rare occasions it reports that the close did not take effect, meaning \
the task was NOT moved and no subtask was dispatched. Do not treat that as a completed close — \
tell the user the task still needs closing by hand.",
        {
            "type": "object",
            "properties": {
                "task_id": {
                    "type": "integer",
                    "description": "The ID of the task whose session to close"
                },
                "token": {
                    "type": "string",
                    "description": "Exit token obtained from wrap_up."
                },
                "action": {
                    "type": "string",
                    "enum": ["rebase", "done", "pr"],
                    "description": "Must match the action passed to wrap_up for this token."
                },
                "pr_url": {
                    "type": "string",
                    "description": "Required when action is 'pr'. The GitHub PR URL returned by gh pr create."
                }
            },
            "required": ["task_id", "token", "action"]
        };

    async "index_repo" => repo_rag::handle_index_repo,
        "Index (or re-index) source files (.md, .rs, .allium) in a repository for semantic search. Creates .dispatch/rag.db in the repo. Indexes up to 50 files per call — if files_remaining > 0, call again until it reaches 0. Safe to re-run; only changed files are re-embedded. Omit repo_path to use the calling task's repo (derived from caller identity).",
        {
            "type": "object",
            "properties": {
                "repo_path": {
                    "type": "string",
                    "description": "Absolute path to the repository root. Omit to use the calling task's repo_path."
                }
            },
            "required": []
        };

    async "search_docs" => repo_rag::handle_search_docs,
        "Semantic search over indexed source files (.md, .rs, .allium) in a repository. Returns ranked chunks with file path and score. Returns empty results (not an error) when the repo has not been indexed yet — call index_repo first. Omit repo_path to use the calling task's repo.",
        {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Natural language search query"
                },
                "repo_path": {
                    "type": "string",
                    "description": "Absolute path to the repository root. Omit to use the calling task's repo_path."
                },
                "limit": {
                    "type": "integer",
                    "description": "Maximum results to return (default 5, max 20)"
                }
            },
            "required": ["query"]
        };

    async "query_usage" => tasks::handle_query_usage,
        "Query aggregated feature usage counts. Returns events grouped by category/action/actor, ordered by count ascending (least-used first). Useful for identifying unused keybindings or MCP tools.",
        {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "description": "Filter by category: 'keybinding' or 'mcp_tool'",
                    "enum": ["keybinding", "mcp_tool"]
                },
                "actor": {
                    "type": "string",
                    "description": "Filter by actor: 'human' or 'agent'",
                    "enum": ["human", "agent"]
                },
                "since": {
                    "type": "string",
                    "description": "ISO 8601 datetime lower bound, e.g. '2026-01-01T00:00:00Z'"
                },
                "limit": {
                    "type": "integer",
                    "description": "Max results (default 50, max 500)"
                }
            }
        }
}

// ---------------------------------------------------------------------------
// MCP handler
// ---------------------------------------------------------------------------

pub async fn handle_mcp(
    State(state): State<Arc<McpState>>,
    Extension(identity_result): Extension<Result<CallerIdentity, IdentityError>>,
    Json(req): Json<JsonRpcRequest>,
) -> Response {
    // JSON-RPC 2.0 §4.1: a Notification (no `id`) must never receive a reply.
    // MCP streamable-HTTP maps this to HTTP 202 Accepted with no body. Replying
    // to `notifications/initialized` (which Claude Code always sends after
    // `initialize`) with `id: null` breaks the client's response schema and
    // aborts the session.
    if req.id.is_none() {
        tracing::debug!(method = %req.method, "received MCP notification (no reply)");
        return StatusCode::ACCEPTED.into_response();
    }

    let id = req.id;
    let response = match req.method.as_str() {
        "initialize" => {
            // Per spec: if the client offers a version we support, echo it
            // back to use that version for the session; otherwise reply with
            // our latest supported version (the client may then abort).
            let client_version = req
                .params
                .as_ref()
                .and_then(|p| p.get("protocolVersion"))
                .and_then(Value::as_str);
            let negotiated = match client_version {
                Some(v) if SUPPORTED_PROTOCOL_VERSIONS.contains(&v) => v,
                _ => SERVER_PROTOCOL_VERSION,
            };
            JsonRpcResponse::ok(
                id,
                json!({
                    "protocolVersion": negotiated,
                    "capabilities": {
                        "tools": {}
                    },
                    "serverInfo": {
                        "name": "dispatch",
                        "version": "0.1.0"
                    }
                }),
            )
        }

        "ping" => JsonRpcResponse::ok(id, json!({})),

        "tools/list" => JsonRpcResponse::ok(id, tool_definitions()),

        "tools/call" => match identity_result.as_ref() {
            Err(e) => JsonRpcResponse::err(id, -32600, e.to_string()),
            Ok(identity) => {
                let params = req.params.unwrap_or(Value::Null);
                let tool_name = params.get("name").and_then(Value::as_str).unwrap_or("");
                let args = params.get("arguments").cloned().unwrap_or(Value::Null);

                let start = std::time::Instant::now();
                let start_utc = Utc::now();
                let resp = dispatch_tool(&state, id, identity, tool_name, args.clone()).await;

                if let CallerIdentity::Task(task_id) = identity {
                    let duration_ms = start.elapsed().as_millis() as u64;
                    let result_value = match &resp.error {
                        Some(err) => serde_json::json!({"error": err.message}),
                        None => resp.result.clone().unwrap_or(Value::Null),
                    };
                    let entry = trajectory::TrajectoryEntry {
                        timestamp: start_utc,
                        task_id: task_id.0,
                        method: tool_name.to_string(),
                        args,
                        result: result_value,
                        duration_ms,
                    };
                    let data_dir = state.data_dir.clone();
                    let bg_done = state.test_hooks.bg_write_done_tx.clone();
                    tokio::spawn(async move {
                        trajectory::append_entry(&data_dir, &entry).await;
                        if let Some(tx) = &bg_done {
                            let _ = tx.send(crate::mcp::BackgroundWrite::Trajectory);
                        }
                    });
                }

                // Fire-and-forget usage recording. Skipped when no tool name was
                // resolved (e.g. malformed request) to avoid recording empty rows.
                if !tool_name.is_empty() {
                    let actor = match identity {
                        CallerIdentity::Task(_) => crate::models::UsageActor::Agent,
                        CallerIdentity::Session => crate::models::UsageActor::Human,
                    };
                    let db = Arc::clone(&state.db);
                    let tool = tool_name.to_string();
                    let bg_done = state.test_hooks.bg_write_done_tx.clone();
                    tokio::spawn(async move {
                        let _ = db
                            .record_usage_event(&crate::models::UsageEvent {
                                category: crate::models::UsageCategory::McpTool,
                                action: tool,
                                detail: None,
                                actor,
                            })
                            .await;
                        if let Some(tx) = &bg_done {
                            let _ = tx.send(crate::mcp::BackgroundWrite::Usage);
                        }
                    });
                }

                // Per MCP spec, tool-execution failures belong in `result` with
                // `isError: true` — not as a JSON-RPC protocol error. Re-wrap any
                // error returned by the tool dispatch path.
                match resp.error {
                    Some(err) => tool_error(resp.id, err.message),
                    None => resp,
                }
            }
        },

        other => JsonRpcResponse::err(id, -32601, format!("Method not found: {other}")),
    };

    (StatusCode::OK, Json(response)).into_response()
}
